// web/src/lib/components/SourceLink.svelte
<script lang="ts">
  import type { Source } from "../types";

  export let source: Source;
  export let text: string | undefined = undefined;

  // Only allow http/https URLs to prevent javascript: XSS
  $: safeUrl =
    source.url.startsWith("http://") || source.url.startsWith("https://")
      ? source.url
      : undefined;

  // Extract domain from URL for display
  $: domain = getDomain(source.url);

  function getDomain(url: string): string {
    try {
      const urlObj = new URL(url);
      return urlObj.hostname.replace("www.", "");
    } catch {
      return url;
    }
  }
</script>

{#if safeUrl}
  <a
    href={safeUrl}
    target="_blank"
    rel="noopener noreferrer"
    class="inline-flex items-center gap-1 text-blue-600 hover:text-blue-500 dark:hover:text-blue-400 text-xs sm:text-sm underline"
    title="{source.title || text || domain} - Open in new tab"
  >
    <span>{text || source.title || domain}</span>
    <svg
      class="w-3 h-3 flex-shrink-0"
      fill="none"
      stroke="currentColor"
      viewBox="0 0 24 24"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"
      />
    </svg>
  </a>
{:else}
  <span class="inline-flex items-center gap-1 text-xs sm:text-sm">
    {text || source.title || domain}
  </span>
{/if}

// design-system/src/components/SourceLink/SourceLink.tsx
import { safeExternalUrl } from "../../utils/url";

export interface SourceLinkProps {
  /** Source URL. Only http/https URLs render as a link — anything else falls back to plain text. */
  url: string;
  /** Optional source title, used for the label and title-attribute fallback. */
  title?: string;
  /** Explicit label override. Falls back to title, then the URL's domain. */
  text?: string;
}

function domainOf(url: string): string {
  try {
    return new URL(url).hostname.replace(/^www\./, "");
  } catch {
    return url;
  }
}

/**
 * Inline external-source citation link — an icon-suffixed underline link
 * that opens in a new tab, with a domain fallback label. Renders as plain
 * text (no link) for any non-http(s) URL.
 */
export function SourceLink({ url, title, text }: SourceLinkProps) {
  const domain = domainOf(url);
  const safeUrl = safeExternalUrl(url);
  const label = text || title || domain;

  if (!safeUrl) {
    return <span className="inline-flex items-center gap-1 text-xs sm:text-sm">{label}</span>;
  }

  return (
    <a
      href={safeUrl}
      target="_blank"
      rel="noopener noreferrer"
      title={`${label} - Open in new tab`}
      className="inline-flex items-center gap-1 text-blue-600 hover:text-blue-500 dark:hover:text-blue-400 text-xs sm:text-sm underline"
    >
      <span>{label}</span>
      <svg className="w-3 h-3 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={2}
          d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"
        />
      </svg>
    </a>
  );
}
