// design-system/src/components/ValidationGradeBadge/ValidationGradeBadge.tsx
import { Tooltip } from "../Tooltip";

export type Grade = "A" | "B" | "C" | "D" | "F";

export interface ValidationGradeInfo {
  grade: Grade;
  score: number;
  summary: string;
}

export interface ValidationGradeBadgeProps {
  grade: ValidationGradeInfo;
  /** Called when the user clicks "View Full Review" inside the popover. */
  onViewReview?: () => void;
}

const gradeColors: Record<Grade, string> = {
  A: "bg-green-100 dark:bg-green-900/40 text-green-800 dark:text-green-200 border-green-300 dark:border-green-700",
  B: "bg-blue-100 dark:bg-blue-900/40 text-blue-800 dark:text-blue-200 border-blue-300 dark:border-blue-700",
  C: "bg-yellow-100 dark:bg-yellow-900/40 text-yellow-800 dark:text-yellow-200 border-yellow-300 dark:border-yellow-700",
  D: "bg-orange-100 dark:bg-orange-900/40 text-orange-800 dark:text-orange-200 border-orange-300 dark:border-orange-700",
  F: "bg-red-100 dark:bg-red-900/40 text-red-800 dark:text-red-200 border-red-300 dark:border-red-700",
};

/**
 * Circular A–F AI-validation grade pill. Clicking it opens a popover with
 * the score, a summary, and a "View Full Review" link.
 */
export function ValidationGradeBadge({ grade, onViewReview }: ValidationGradeBadgeProps) {
  const colorClass = gradeColors[grade.grade];

  return (
    <Tooltip
      trigger={
        <span
          aria-label={`Validation Grade: ${grade.grade}`}
          className={`grade-badge inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full border text-sm font-semibold cursor-pointer transition-all duration-150 hover:shadow-md active:scale-95 ${colorClass}`}
        >
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
            />
          </svg>
          <span className="text-base font-bold leading-none">{grade.grade}</span>
          <span className="text-xs font-medium opacity-75">Validation</span>
        </span>
      }
    >
      <div className="flex items-center justify-between mb-2">
        <span className="text-sm font-semibold text-content">AI Validation Grade</span>
        <span className={`px-2 py-0.5 rounded-sm text-sm font-bold border ${colorClass}`}>{grade.grade}</span>
      </div>
      <p className="text-sm font-medium text-content-muted mb-1">Score: {grade.score}/100</p>
      <p className="text-sm text-content-muted mb-3">{grade.summary}</p>
      <p className="text-xs text-content-subtle mb-3 leading-relaxed">
        Multiple AI models independently review each race profile for factual accuracy, source quality,
        completeness, and neutrality. The grade reflects the average score across all reviewers.
      </p>
      <button
        type="button"
        onClick={onViewReview}
        className="inline-flex items-center gap-1 text-sm font-medium text-blue-600 dark:text-blue-400 hover:text-blue-800 dark:hover:text-blue-300 cursor-pointer transition-colors duration-150"
      >
        View Full Review
        <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 14l-7 7m0 0l-7-7m7 7V3" />
        </svg>
      </button>
    </Tooltip>
  );
}

// web/src/lib/components/ValidationGradeBadge.svelte
<script lang="ts">
  import type { ValidationGrade } from "$lib/types";
  import { scrollBehavior } from "$lib/utils/motion";

  export let grade: ValidationGrade;

  let showPopover = false;

  function gradeColor(g: string): string {
    switch (g) {
      case "A":
        return "bg-green-100 dark:bg-green-900/40 text-green-800 dark:text-green-200 border-green-300 dark:border-green-700";
      case "B":
        return "bg-teal-100 dark:bg-teal-900/40 text-teal-800 dark:text-teal-200 border-teal-300 dark:border-teal-700";
      case "C":
        return "bg-yellow-100 dark:bg-yellow-900/40 text-yellow-800 dark:text-yellow-200 border-yellow-300 dark:border-yellow-700";
      case "D":
        return "bg-orange-100 dark:bg-orange-900/40 text-orange-800 dark:text-orange-200 border-orange-300 dark:border-orange-700";
      case "F":
        return "bg-red-100 dark:bg-red-900/40 text-red-800 dark:text-red-200 border-red-300 dark:border-red-700";
      default:
        return "bg-surface-alt text-content border-stroke";
    }
  }

  function scrollToReview() {
    showPopover = false;
    const el = document.getElementById("ai-review");
    if (el) el.scrollIntoView({ behavior: scrollBehavior() });
  }
</script>

<div class="grade-wrapper">
  <button
    class="grade-badge {gradeColor(grade.grade)}"
    on:click={() => (showPopover = !showPopover)}
    on:keydown={(e) => e.key === "Escape" && (showPopover = false)}
    aria-label="Automated research score: {grade.grade}"
    aria-expanded={showPopover}
    aria-controls={showPopover ? "validation-grade-popover" : undefined}
  >
    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
      />
    </svg>
    <span class="grade-letter">{grade.grade}</span>
    <span class="grade-label">Research score</span>
  </button>

  {#if showPopover}
    <!-- svelte-ignore a11y-click-events-have-key-events -->
    <!-- svelte-ignore a11y-no-static-element-interactions -->
    <div class="popover-backdrop" on:click={() => (showPopover = false)}></div>
    <div
      class="popover"
      id="validation-grade-popover"
      role="dialog"
      aria-label="Automated research score details"
    >
      <div class="popover-header">
        <span class="popover-title">Automated research score</span>
        <span class="popover-grade {gradeColor(grade.grade)}"
          >{grade.grade}</span
        >
      </div>
      <p class="popover-score">Score: {grade.score}/100</p>
      <p class="popover-summary">{grade.summary}</p>
      <p class="popover-explain">
        Separate AI models review source quality, completeness, consistency, and
        neutrality. The score summarizes those research checks; it is not a
        guarantee that every claim is correct.
      </p>
      <button class="popover-link" on:click={scrollToReview}>
        View review details
        <svg
          class="w-3.5 h-3.5"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M19 14l-7 7m0 0l-7-7m7 7V3"
          />
        </svg>
      </button>
    </div>
  {/if}
</div>

<style lang="postcss">
  .grade-wrapper {
    @apply relative inline-flex;
  }

  .grade-badge {
    @apply inline-flex min-h-11 items-center gap-1.5 px-3 py-1.5 rounded-full border
           text-sm font-semibold cursor-pointer transition-all duration-150
           hover:shadow-md active:scale-95;
  }

  .grade-letter {
    @apply text-base font-bold leading-none;
  }

  /* Full-opacity text: the old 75% opacity dropped green-800 on green-100
     below 4.5:1. */
  .grade-label {
    @apply text-xs font-medium;
  }

  .popover-backdrop {
    @apply fixed inset-0 z-40;
  }

  .popover {
    @apply absolute top-full left-0 mt-2 z-50 w-72 max-w-[calc(100vw-2rem)]
           bg-surface border border-stroke rounded-xl shadow-lg p-4
           sm:left-auto sm:right-0;
  }

  .popover-header {
    @apply flex items-center justify-between mb-2;
  }

  .popover-title {
    @apply text-sm font-semibold text-content;
  }

  .popover-grade {
    @apply px-2 py-0.5 rounded text-sm font-bold border;
  }

  .popover-score {
    @apply text-sm font-medium text-content-muted mb-1;
  }

  .popover-summary {
    @apply text-sm text-content-muted mb-3;
  }

  .popover-explain {
    @apply text-xs text-content-subtle mb-3 leading-relaxed;
  }

  .popover-link {
    @apply inline-flex min-h-10 items-center gap-1 text-sm font-medium
           text-primary hover:underline
           cursor-pointer transition-colors duration-150;
  }
</style>
